// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqfiqmttrbjokxgstywl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZmlxbXR0cmJqb2t4Z3N0eXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODEwNjgsImV4cCI6MjA2ODk1NzA2OH0.uAP9Kc0t0vbt4th2NBD46M2cAWhV7jePbICQ7OqrRZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});